[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322

[auth]
site_url = "https://maningo.hosthampton.com"
additional_redirect_urls = ["http://localhost:3000", "http://localhost:3001"]
jwt_expiry = 3600
enable_signup = true
